package localization

import androidx.compose.ui.text.intl.Locale

fun isKoreanUi(): Boolean = Locale.current.language == "ko"

fun localized(english: String): String = translateUi(english, Locale.current.language)

fun localized(english: String, korean: String): String = if (isKoreanUi()) korean else english

fun localizedClockTime(hour: Int, minute: Int): String =
    clockTimeForLanguage(hour, minute, Locale.current.language)

internal fun clockTimeForLanguage(hour: Int, minute: Int, language: String): String {
    val normalizedHour = ((hour % 24) + 24) % 24
    val hour12 = when {
        normalizedHour == 0 -> 12
        normalizedHour > 12 -> normalizedHour - 12
        else -> normalizedHour
    }
    val clock = "$hour12:${minute.coerceIn(0, 59).toString().padStart(2, '0')}"
    val meridiem = if (normalizedHour < 12) {
        if (language == "ko") "오전" else "AM"
    } else {
        if (language == "ko") "오후" else "PM"
    }
    return if (language == "ko") "$meridiem $clock" else "$clock $meridiem"
}

internal fun translateUi(english: String, language: String): String = if (language == "ko") korean[english] ?: english else english

private val korean = mapOf(
    "DeepSleep" to "깊은 수면",
    "Nap" to "낮잠",
    "DeepNap" to "깊은 낮잠",
    "Walk" to "걷기",
    "Run" to "달리기",
    "OpenWorkout" to "자유 운동",
    "Cancel" to "취소",
    "Remove" to "제거",
    "OK" to "확인",
    "Unknown error" to "알 수 없는 오류",
    "Notifications" to "알림",
    "Not yet implemented" to "아직 지원하지 않는 기능입니다",
    "Save" to "저장",
    "Back" to "뒤로",
    "Health" to "건강",
    "Average" to "평균",
    "None" to "없음",
    "Search" to "검색",
    "Done icon" to "완료",
    "Close" to "닫기",
    "Screenshot" to "스크린샷",
    "Test" to "테스트",
    "Select" to "선택",
    "Unknown version" to "알 수 없는 버전",
    "Delete" to "삭제",
    "Notified only" to "알림을 받은 앱만",
    "AM" to "오전",
    "PM" to "오후",
    "Watch" to "시계",
    "Title" to "제목",
    "Body" to "내용",
    "Install" to "설치",
    "Battery" to "배터리",
    "Loading..." to "불러오는 중…",
    "Default" to "기본값",
    "Settings" to "설정",
    "Apps" to "앱",
    "Current Location" to "현재 위치",
    "Sign in" to "로그인",
    "Retry" to "다시 시도",
    "Reply" to "답장",
    "Add rule" to "규칙 추가",
    "Attach Files" to "파일 첨부",
    "Add Image" to "사진 추가",
    "Download" to "다운로드",
    "Collapse" to "접기",
    "Expand" to "펼치기",
    "Done" to "완료",
    "Add Watch" to "시계 추가",
    "Add Classic Watch" to "클래식 시계 추가",
    "More options" to "더 보기",
    "Are you sure?" to "정말 진행하시겠습니까?",
    "Rename" to "이름 변경",
    "Debug" to "디버그",
    "Send" to "보내기",
    "Bug Report" to "버그 제보",
    "Share" to "공유",
    "Error Pairing" to "연결 오류",
    "Phone" to "휴대폰",
    "Next" to "다음",
    "Today" to "오늘",
    "Deep sleep" to "깊은 수면",
    "Light sleep" to "얕은 수면",
    "Awake" to "깨어 있음",
    "Typical" to "평소",
    "Color" to "색상",
    "Select color" to "색상 선택",
    "Reset" to "초기화",
    "Not compatible with this watch" to "이 시계와 호환되지 않습니다",
    "Not natively compatible with this watch, but can be scaled" to "이 시계용은 아니지만 크기를 맞춰 사용할 수 있습니다",
    "Faces" to "워치페이스",
    "Selected" to "선택됨",
    "Show Incompatible" to "호환되지 않는 항목도 표시",
    "Vibration Pattern" to "진동 패턴",
    "Fixed Location" to "지정한 위치",
    "Quiet Time" to "방해 금지",
    "Details" to "자세히",
    "Refresh" to "새로고침",
    "Quick replies" to "빠른 답장",
    "All" to "전체",
    "Disabled" to "사용 안 함",
    "<Empty>" to "<비어 있음>",
    "Local Only" to "기기에서만",
    "Regex" to "정규식",
    "Text" to "텍스트",
    "Edit rule" to "규칙 수정",
    "Both" to "둘 다",
    "Add To Watch" to "시계에 추가",
    "Failed to add app" to "앱을 추가하지 못했습니다",
    "Move To Top" to "맨 위로",
    "External Link" to "외부 링크",
    "Timeline" to "타임라인",
    "Active" to "활성",
    "From the store" to "스토어에서",
    "Clear filters for more results" to "필터를 지우면 더 많은 결과를 볼 수 있습니다",
    "In My Collection" to "내 보관함",
    "Permissions" to "권한",
    "All permissions granted!" to "필요한 권한이 모두 허용됐습니다!",
    "Continue" to "계속",
    "Speech Recognition" to "음성 인식",
    "Error occurred. Please try again later." to "오류가 발생했습니다. 잠시 후 다시 시도해 주십시오.",
    "Error starting download. Please try again later." to "다운로드를 시작하지 못했습니다. 잠시 후 다시 시도해 주십시오.",
    "Populate fake health data" to "테스트용 건강 데이터 채우기",
    "What’s new in PebbleOS" to "PebbleOS의 새로운 기능",
    "Getting Started & Troubleshooting" to "시작하기 및 문제 해결",
    "Override the default on the watch" to "시계의 기본 설정 대신 사용",
    "Reminder Vibration Pattern" to "리마인더 진동 패턴",
    "This device doesn't support local speech recognition" to "이 기기는 기기 내 음성 인식을 지원하지 않습니다",
    "You need to be signed in to use cloud speech recognition" to "클라우드 음성 인식을 쓰려면 로그인해 주십시오",
    "Spoken Language" to "말하는 언어",
    "Automatic" to "자동",
    "Cloud Recognition Provider" to "클라우드 음성 인식 서비스",
    "Sign in to backup your Pebble account to backup apps, settings, etc" to "앱과 설정 등을 백업하려면 Pebble 계정에 로그인해 주십시오",
    "6 hours" to "6시간",
    "Add" to "추가",
    "Please sign in before submitting a bug report" to "버그를 제보하려면 먼저 로그인해 주십시오",
    "Creating bug report..." to "버그 제보를 준비하는 중…",
    "Sign In" to "로그인",
    "My Bug Reports" to "내 버그 제보",
    "Unknown" to "알 수 없음",
    "Uploading attachments" to "첨부 파일을 올리는 중",
    "Skip Setup" to "설정 건너뛰기",
    "Attach files" to "파일 첨부",
    "Get started" to "시작하기",
    "Get Set Up" to "설정 시작",
    "Speech recognition switched to Cloud Only" to "클라우드 음성 인식으로 전환했습니다",
    "Download Required" to "다운로드 필요",
    "Your device may struggle with larger models, a reduced accuracy model will be used." to "이 기기에서는 큰 모델을 실행하기 어려워 정확도가 조금 낮은 가벼운 모델을 사용합니다.",
    "Manage Models" to "모델 관리",
    "Recommended for your device" to "이 기기에 추천",
    "Higher accuracy for English" to "영어 인식 정확도가 더 높습니다",
    "Sort Options" to "정렬 옵션",
    "Show system apps" to "시스템 앱 표시",
    "All Apps" to "모든 앱",
    "Mute All" to "모두 끄기",
    "Enable All" to "모두 켜기",
    "New app default" to "새 앱의 기본 설정",
    "Notification History" to "알림 기록",
    "App Settings" to "앱 설정",
    "Enable Bluetooth to connect a Pebble" to "페블을 연결하려면 블루투스를 켜주십시오",
    "Bluetooth is disabled" to "블루투스가 꺼져 있습니다",
    "Stop Scanning" to "검색 중지",
    "Add a Pebble" to "페블 추가",
    "Scan" to "검색",
    "Add Index 01" to "Index 01 추가",
    "Classic Watch" to "클래식 시계",
    "Enable bluetooth to connect to your watch." to "시계를 연결하려면 블루투스를 켜주십시오.",
    "Scanning for devices..." to "기기를 찾는 중…",
    "Press the button on your Index 01 to wake it." to "Index 01의 버튼을 눌러 깨워주십시오.",
    "Can't find your Index 01? Press the button on the ring to wake it up." to "Index 01이 보이지 않습니까? 링의 버튼을 눌러 깨워주십시오.",
    "If you have any other Pebble apps installed on your phone, please uninstall them - " to "휴대폰에 다른 페블 앱이 설치돼 있다면 삭제해 주십시오. ",
    "connection to the watch will not work while they are installed." to "다른 페블 앱이 설치된 상태에서는 시계 연결이 안 될 수 있습니다.",
    "Index 01 already paired" to "Index 01이 이미 연결돼 있습니다",
    "An Index 01 is already paired to this phone. To pair a different Index 01, first unpair the existing one." to "이 휴대폰에 Index 01이 이미 연결돼 있습니다. 다른 링을 연결하려면 기존 연결을 먼저 해제해 주십시오.",
    "Failsafe mode" to "안전 모드",
    "Production test mode" to "출고 테스트 모드",
    "Available to pair" to "연결 가능",
    "Updating..." to "업데이트 중…",
    "Ready" to "준비됨",
    "Pairing failure" to "연결 실패",
    "Pairing..." to "연결 중…",
    "Pair" to "연결",
    "Restore firmware" to "펌웨어 복구",
    "Restoring - please wait..." to "복구 중입니다. 잠시 기다려주십시오…",
    "Limited background access" to "백그라운드 실행이 제한돼 있습니다",
    "Enable background access" to "백그라운드 실행 허용",
    "Pairing issue detected" to "연결 문제가 감지됐습니다",
    "Device already paired" to "이미 연결된 기기",
    "Error" to "오류",
    "This device is having trouble pairing. Please follow the instructions below to recover it:" to "기기를 연결하지 못했습니다. 아래 안내에 따라 복구해 주십시오.",
    "1. Go to Settings > Bluetooth" to "1. 설정 > 블루투스로 이동해 주십시오",
    "2. Find e.g. 'Pebble Index ABC' in the list of devices" to "2. 기기 목록에서 'Pebble Index ABC' 같은 이름을 찾아주십시오",
    ". If it's not there, continue." to ". 목록에 없다면 다음 단계로 넘어가십시오.",
    "4. Reset the ring by pressing the button in an 'SOS' sequence as shown below." to "4. 아래처럼 SOS 순서로 버튼을 눌러 링을 초기화해 주십시오.",
    "This device is already paired to another phone." to "이 기기는 다른 휴대폰에 이미 연결돼 있습니다.",
    "Please reset the ring by pressing the button in an 'SOS' sequence as shown below, then try pairing again." to "아래처럼 SOS 순서로 버튼을 눌러 링을 초기화한 뒤 다시 연결해 주십시오.",
    "After unpairing, reset the ring by pressing the button in an 'SOS' sequence as shown below." to "연결을 해제한 뒤 아래처럼 SOS 순서로 버튼을 눌러 링을 초기화해 주십시오.",
    "Short (3 times) LONG (1 second, 3 times) short (3 times)" to "짧게 3번 → 길게 1초씩 3번 → 짧게 3번",
    "You'll see the light flash red green blue repeatedly when successful." to "완료되면 빨강·초록·파랑 불빛이 번갈아 깜빡입니다.",
    "Need more help? View detailed instructions" to "도움이 더 필요합니까? 자세한 안내 보기",
    "Select All" to "모두 선택",
    "Remove Nickname" to "별명 지우기",
    "Failed to download firmware" to "펌웨어를 내려받지 못했습니다",
    "Failed to parse manifest" to "펌웨어 정보를 읽지 못했습니다",
    "App Updates" to "앱 업데이트",
    "Update available — tap to install" to "새 버전이 있습니다. 눌러서 설치해 주십시오",
    "Check for app updates" to "앱 업데이트 확인",
    "Language Packs" to "언어팩",
    "Developer connection active" to "개발자 연결 활성화됨",
    "Update PebbleOS" to "PebbleOS 업데이트",
    "Please go to system bluetooth settings, and unpair this device." to "휴대폰의 블루투스 설정에서 이 기기의 연결을 해제해 주십시오.",
    "Connection failing" to "연결이 계속 실패하고 있습니다",
    "Can't connect to watch" to "시계에 연결할 수 없습니다",
    "Make sure your watch is powered on and nearby. " to "시계가 켜져 있고 가까이에 있는지 확인해 주십시오. ",
    "If it still won't connect, open Bluetooth settings, " to "계속 연결되지 않으면 블루투스 설정을 열고 ",
    "Error Connecting - Restart Your Watch" to "연결 오류 — 시계를 다시 시작해 주십시오",
    "Restart your watch" to "시계 다시 시작",
    "Your watch needs to be restarted before it can connect. " to "연결하려면 시계를 다시 시작해야 합니다. ",
    "Press and hold the back button (top-left) for about 15 seconds " to "왼쪽 위의 뒤로 버튼을 약 15초간 눌러 ",
    "until the watch restarts, then try connecting again." to "시계를 다시 시작한 뒤 연결을 시도해 주십시오.",
    "Disconnect" to "연결 끊기",
    "Connect" to "연결",
    "Open Bluetooth settings" to "블루투스 설정 열기",
    "Health Settings" to "건강 설정",
    "Day" to "일",
    "Week" to "주",
    "Month" to "월",
    "Previous" to "이전",
    "Steps" to "걸음 수",
    "No activity data" to "활동 기록이 없습니다",
    "Wear your watch to start tracking steps" to "시계를 착용하면 걸음 수를 기록합니다",
    "Total" to "합계",
    "Sleep" to "수면",
    "No sleep data" to "수면 기록이 없습니다",
    "Wear your watch to bed to track sleep" to "시계를 착용하고 자면 수면을 기록합니다",
    "Avg Deep" to "평균 깊은 수면",
    "Avg Fall Asleep" to "평균 취침 시각",
    "Avg Wake Up" to "평균 기상 시각",
    "Distance" to "거리",
    "Average distance" to "평균 거리",
    "Calories" to "칼로리",
    "Average calories" to "평균 칼로리",
    "Active time" to "활동 시간",
    "Average active time" to "평균 활동 시간",
    "No data" to "기록 없음",
    "latest bpm" to "최근 심박수",
    "avg bpm" to "평균 심박수",
    "Resting" to "안정 시",
    "Heart Rate" to "심박수",
    "No heart rate data" to "심박수 기록이 없습니다",
    "Heart rate is measured automatically by your watch" to "시계가 심박수를 자동으로 측정합니다",
    "Wear your watch to start tracking" to "시계를 착용하면 기록을 시작합니다",
    "Yesterday" to "어제",
    "Presets" to "프리셋",
    "Hex" to "색상 코드",
    "My Watchfaces" to "내 워치페이스",
    "My Apps" to "내 앱",
    "Order" to "순서",
    "Order by recently used" to "최근 사용순",
    "Order manually" to "직접 정렬",
    "Daily" to "일상",
    "Tools & Utilities" to "도구 및 유틸리티",
    "Remotes" to "리모컨",
    "Health & Fitness" to "건강 및 운동",
    "Games" to "게임",
    "6 PM" to "오후 6시",
    "12 AM" to "오전 12시",
    "6 AM" to "오전 6시",
    "12 PM" to "오후 12시",
    "Calendar Settings" to "캘린더 설정",
    "Calendar permission missing" to "캘린더 권한이 필요합니다",
    "Approve" to "허용",
    "Not synced by Android - toggle checkbox to ask Android to sync" to "안드로이드에서 동기화하지 않는 캘린더입니다. 체크하면 동기화를 요청합니다",
    "Vibrations" to "진동",
    "Test Vibe Pattern" to "진동 패턴 시험",
    "Delete Pattern" to "패턴 삭제",
    "Choose Vibration Pattern" to "진동 패턴 선택",
    "Add Custom Pattern" to "직접 만든 패턴 추가",
    "Tap custom pattern" to "눌러서 패턴 만들기",
    "Custom Tapped Pattern" to "직접 누른 패턴",
    "Pattern Name" to "패턴 이름",
    "Select vibration pattern" to "진동 패턴 선택",
    "Refresh Weather" to "날씨 새로고침",
    "Weather Locations" to "날씨 지역",
    "Add location" to "지역 추가",
    "Search Location" to "지역 검색",
    "Add Weather Location" to "날씨 지역 추가",
    "Uses your device's location" to "휴대폰의 현재 위치를 사용합니다",
    "Search for a specific address" to "주소로 검색",
    "Address" to "주소",
    "Enter city or address" to "도시나 주소 입력",
    "Couldn't search for locations. Check your connection and try again." to "지역을 검색하지 못했습니다. 인터넷 연결을 확인한 뒤 다시 시도해 주십시오.",
    "Type to search for locations..." to "검색할 지역을 입력해 주십시오…",
    "Remove Location" to "지역 삭제",
    "Reset To Defaults?" to "기본값으로 되돌리시겠습니까?",
    "Reset all settings to defaults" to "모든 설정을 기본값으로 되돌리기",
    "Reset To Defaults" to "기본값으로 초기화",
    "Reset all watch settings to defaults" to "시계의 모든 설정을 기본값으로 되돌리기",
    "Backlight" to "백라이트",
    "Motion Backlight" to "움직이면 백라이트 켜기",
    "Airplane Mode" to "비행기 모드",
    "Timeline Past" to "지난 타임라인",
    "Timeline Future" to "다가오는 타임라인",
    "Contact Notifications" to "연락처별 알림",
    "Star a contact to always receive notifications from them, even if e.g. the app is muted" to "연락처에 별표를 표시하면 앱 알림을 꺼도 해당 연락처의 알림은 받습니다",
    "Star" to "별표",
    "Health Debug Stats" to "건강 진단 통계",
    "Refresh health data" to "건강 기록 새로고침",
    "Today's Steps" to "오늘의 걸음 수",
    "Last Night's Sleep" to "어젯밤 수면",
    "Typical steps by weekday" to "요일별 평소 걸음 수",
    "Typical sleep by weekday" to "요일별 평소 수면",
    "Loading health statistics..." to "건강 통계를 불러오는 중…",
    "Battery analytics service is not configured" to "배터리 분석 서비스가 설정되지 않았습니다",
    "Sign in to view your battery analytics" to "배터리 사용 기록을 보려면 로그인해 주십시오",
    "You must be signed into your Pebble account to view your Battery usage." to "배터리 사용 기록을 보려면 Pebble 계정에 로그인해 주십시오.",
    "Couldn't load your Battery usage. Check your connection and try again." to "배터리 사용 기록을 불러오지 못했습니다. 인터넷 연결을 확인한 뒤 다시 시도해 주십시오.",
    "You need 'Send watch analytics' enabled to view your Battery usage." to "배터리 사용 기록을 보려면 '시계 분석 정보 보내기'를 켜주십시오.",
    "Open settings" to "설정 열기",
    "Reorder" to "순서 변경",
    "Add reply" to "답장 추가",
    "Unsaved changes" to "저장하지 않은 변경 사항",
    "You have unsaved changes to your quick replies." to "빠른 답장에 저장하지 않은 변경 사항이 있습니다.",
    "Discard" to "변경 취소",
    "Contacts" to "연락처",
    "Rules" to "규칙",
    "History" to "기록",
    "Enabled" to "사용",
    "Debug Firmware Update" to "펌웨어 업데이트 진단",
    "Update complete" to "업데이트 완료",
    "Idle" to "대기 중",
    "Sideload FW" to "펌웨어 파일 설치",
    "No FW available" to "설치할 펌웨어가 없습니다",
    "Sideload from container" to "컨테이너에서 설치",
    "Starting" to "시작 중",
    "Waiting for reboot" to "다시 시작하기를 기다리는 중",
    "Install firmware" to "펌웨어 설치",
    "Loop Test" to "반복 테스트",
    "Loop From PRF" to "복구 펌웨어부터 반복",
    "Cancel update" to "업데이트 취소",
    "Displayed" to "표시됨",
    "Sent" to "전송됨",
    "Group Summary" to "알림 그룹 요약",
    "App Muted" to "앱 알림 꺼짐",
    "Channel Muted" to "알림 채널 꺼짐",
    "Duplicate" to "중복",
    "Contact Muted" to "연락처 알림 꺼짐",
    "Screen On" to "화면 켜짐",
    "Rule Filtered" to "규칙에 따라 제외됨",
    "Empty" to "비어 있음",
    "App Notifications" to "앱 알림",
    "Channels" to "알림 채널",
    "Default Group" to "기본 그룹",
    "Allow duplicate notifications" to "중복 알림 허용",
    "Send images" to "사진 보내기",
    "Status: Muted (Always)" to "상태: 항상 알림 끄기",
    "Status: Muted (Weekdays)" to "상태: 평일에 알림 끄기",
    "Status: Muted (Weekends)" to "상태: 주말에 알림 끄기",
    "Notification filter rules" to "알림 필터 규칙",
    "No notification rules" to "알림 규칙이 없습니다",
    "Matching notifications will be blocked:" to "다음 조건에 맞는 알림을 차단합니다:",
    "Title+Body" to "제목+내용",
    "case-sensitive" to "대소문자 구분",
    "case-insensitive" to "대소문자 구분 안 함",
    "Delete rule" to "규칙 삭제",
    "Invalid regex" to "올바르지 않은 정규식",
    "Match type" to "일치 방식",
    "Match field" to "검사할 항목",
    "Pattern" to "패턴",
    "Case sensitive" to "대소문자 구분",
    "View Notifications" to "알림 보기",
    "Are you sure you want to remove this app from your Pebble?" to "페블에서 이 앱을 제거하시겠습니까?",
    "Hearts" to "좋아요",
    "Start App" to "앱 실행",
    "Start Watchface" to "워치페이스 실행",
    "This app's settings page may not work any more" to "이 앱의 설정 페이지가 더 이상 작동하지 않을 수 있습니다",
    "COMPANION" to "연결 앱",
    "DESCRIPTION" to "설명",
    "DEVELOPER" to "개발자",
    " (sideloaded)" to " (파일로 설치됨)",
    "VERSION" to "버전",
    "SOURCE CODE" to "소스 코드",
    "WEBSITE LINK" to "웹사이트",
    "CONTACT DEVELOPER" to "개발자에게 연락",
    "Send Message" to "메시지 보내기",
    "CHANGELOG" to "변경 사항",
    "View" to "보기",
    "Changelog" to "변경 사항",
    "Dismiss" to "닫기",
    "STORE" to "스토어",
    "Location" to "위치",
    "Can access health data" to "건강 기록 접근 가능",
    "Can access location" to "위치 접근 가능",
    "Can create timeline pins" to "타임라인 항목 생성 가능",
    "Watchface" to "워치페이스",
    "WatchApp" to "시계 앱",
    "No connected watch" to "연결된 시계가 없습니다",
    "Sideload App" to "앱 파일 설치",
    "Loading Locker" to "보관함을 불러오는 중",
    "Configure Feeds" to "피드 설정",
    "From my watchfaces" to "내 워치페이스에서",
    "From my apps" to "내 앱에서",
    "See all" to "모두 보기",
    "Please enter a message." to "메시지를 입력해 주십시오.",
    "Please sign in again." to "다시 로그인해 주십시오.",
    "Your email address must be verified before contacting developers." to "개발자에게 연락하려면 이메일 인증이 필요합니다.",
    "Network error. Please try again." to "네트워크 오류입니다. 다시 시도해 주십시오.",
    "Contact the developer" to "개발자에게 연락",
    "Message sent. The developer will receive an email and may reply to you directly." to "메시지를 보냈습니다. 개발자에게 이메일이 전달되며 직접 답장을 받을 수 있습니다.",
    "You need to sign in to contact the developer." to "개발자에게 연락하려면 로그인해 주십시오.",
    "Message" to "메시지",
    "Add files" to "파일 추가",
    "Add photos" to "사진 추가",
    "Send message" to "메시지 보내기",
    "Icons" to "아이콘",
    "Search Icons" to "아이콘 검색",
    "Icon" to "아이콘",
    "Select icon" to "아이콘 선택",
    "Hide missing permission warnings" to "권한 경고 숨기기",
    "Don't show a badge on Settings when permissions are missing" to "권한이 부족해도 설정에 배지를 표시하지 않습니다",
    "Sideload firmware?" to "펌웨어 파일을 설치하시겠습니까?",
    "firmware from sources you trust." to "믿을 수 있는 곳에서 받은 펌웨어만 설치해 주십시오.",
    "Index Permissions" to "Index 권한",
    "Please grant the following permissions:" to "다음 권한을 허용해 주십시오:",
    "Clear search" to "검색어 지우기",
    "About" to "정보",
    "Get Help" to "도움말",
    "Defaults" to "기본 설정",
    "Quick Launch" to "빠른 실행",
    "General" to "일반",
    "Calendar" to "캘린더",
    "Display" to "화면",
    "Weather" to "날씨",
    "Time" to "시간",
    "Connectivity" to "연결",
    "Music" to "음악",
    "Other" to "기타",
    "Diagnostics" to "진단",
    "Bundled Plugins" to "내장 플러그인",
    "This will wipe all existing health data and replace it with 30 days of fake data. This cannot be undone." to "기존 건강 기록을 모두 지우고 30일치 테스트 데이터로 바꿉니다. 되돌릴 수 없습니다.",
    "Wipe & Populate" to "지우고 채우기",
    "App Version" to "앱 버전",
    "What’s new in the app" to "앱의 새로운 기능",
    "New Bug Report" to "새 버그 제보",
    "Please report a bug if anything went wrong!" to "문제가 생기면 버그를 제보해 주십시오!",
    "View My Bug Reports" to "내 버그 제보 보기",
    "Configure Appstore Sources" to "앱스토어 소스 설정",
    "App Theme" to "앱 테마",
    "Imperial Units" to "야드·파운드 단위",
    "Restore System app positions" to "시스템 앱 위치 복원",
    "Restore system apps to their usual position at the top of the menu" to "시스템 앱을 메뉴 맨 위의 원래 위치로 되돌립니다",
    "Background Refresh Interval" to "백그라운드 갱신 간격",
    "How often to check for updates, update apps from store, etc" to "업데이트 확인과 스토어 앱 갱신 등을 실행할 간격입니다",
    "Enable Index Feed" to "Index 피드 사용",
    "Foreground Service" to "백그라운드 연결 유지",
    "Show foreground service notification to keep app alive in background" to "앱이 백그라운드에서도 실행되도록 상시 알림을 표시합니다",
    "Watch fully charged" to "시계 충전 완료 알림",
    "Notify on this phone when a watch finishes charging" to "시계 충전이 끝나면 이 휴대폰으로 알립니다",
    "Preset messages for notification replies on the watch (canned messages)" to "시계에서 알림에 답장할 때 쓸 문구입니다",
    "Always send notifications" to "항상 알림 보내기",
    "Send notifications to the watch even when the phone screen is on" to "휴대폰 화면이 켜져 있어도 시계에 알림을 보냅니다",
    "Respect Phone Do Not Disturb" to "휴대폰의 방해 금지 설정 따르기",
    "Mute phone notification effects" to "휴대폰 알림 소리·진동 끄기",
    "Mute phone call effects" to "휴대폰 전화 소리·진동 끄기",
    "Use vibration patterns from OS" to "휴대폰의 진동 패턴 사용",
    "If there is a vibration pattern defined by the app which created a notification, use it on the watch (unless overridden)" to "알림을 보낸 앱에 진동 패턴이 있으면 시계에서도 사용합니다. 별도로 지정한 패턴이 있으면 그 설정을 따릅니다",
    "Send notification images" to "알림 사진 보내기",
    "Show photos sent in messages on the watch. Can also be turned off per app on the Notifications tab." to "메시지에 담긴 사진을 시계에 표시합니다. 알림 탭에서 앱별로 끌 수도 있습니다.",
    "Send local-only notifications to watch" to "휴대폰 전용 알림도 시계에 보내기",
    "Android recommends not forwarding notifications marked as local-only to external devices - check to override this" to "안드로이드가 외부 기기로 보내지 않도록 지정한 알림도 시계에 보냅니다",
    "Enable showsUserInterface actions" to "휴대폰 화면을 여는 알림 동작 사용",
    "Include notification actions which are marked as opening a user interface on the phone" to "휴대폰에서 화면을 여는 알림 버튼도 포함합니다",
    "Store notifications for" to "알림 보관 기간",
    "How long notifications are stored for. This enabled better deduplicating, and powers the notification history view" to "중복 알림을 걸러내고 알림 기록을 보여주기 위해 알림을 보관하는 기간입니다",
    "Days" to "일",
    "Store disabled notifications" to "차단한 알림도 기록",
    "Disable Companion Device Manager" to "안드로이드 기기 연결 관리자 사용 안 함",
    "Don't use Android's Companion Device Manager to connect. Only use this option if the app crashes every time you press 'connect' and you cannot get past this step. This will disable certain features (including Notification Channels), and certain permissions will need to be granted manually." to "'연결'을 누를 때마다 앱이 종료돼 진행할 수 없는 경우에만 켜주십시오. 알림 채널 등 일부 기능을 사용할 수 없고, 필요한 권한을 직접 허용해야 합니다.",
    "Ignore Missing PRF" to "복구 펌웨어 누락 무시",
    "Ignore missing PRF when connecting to development watches" to "개발용 시계 연결 시 복구 펌웨어가 없어도 계속 진행합니다",
    "Use reversed PPoG" to "역방향 PPoG 사용",
    "Enable Calendar" to "캘린더 사용",
    "Show calendar pins on timeline" to "타임라인에 캘린더 일정 표시",
    "Calendar Reminders" to "일정 미리 알림",
    "Alerts before calendar events" to "일정 시작 전에 알립니다",
    "Declined Events" to "거절한 일정",
    "Display declined calendar events" to "거절한 캘린더 일정도 표시합니다",
    "Calendars" to "캘린더 목록",
    "Configure which calendars to display" to "표시할 캘린더 선택",
    "Enable Health Tracking" to "건강 기록 사용",
    "Heart Rate Monitor" to "심박수 측정",
    "Allow the watch to measure heart rate" to "시계에서 심박수를 측정합니다",
    "Background Sampling" to "평상시 측정 간격",
    "How often the watch checks your heart rate when you're not in a workout. This can have an impact on battery life." to "운동 중이 아닐 때 심박수를 측정하는 간격입니다. 배터리 사용 시간에 영향을 줄 수 있습니다.",
    "Every 10 minutes" to "10분마다",
    "Every 30 minutes" to "30분마다",
    "Every hour" to "1시간마다",
    "Off" to "끄기",
    "HR During Activities" to "활동 중 심박수 측정",
    "Continuously track heart rate during detected walks and runs. This can have an impact on battery life." to "걷기나 달리기가 감지되면 심박수를 계속 측정합니다. 배터리 사용 시간에 영향을 줄 수 있습니다.",
    "Activity Insights" to "활동 분석 알림",
    "Receive notifications with insights about your activity" to "활동 기록을 분석한 알림을 받습니다",
    "Sleep Insights" to "수면 분석 알림",
    "Receive notifications with insights about your sleep" to "수면 기록을 분석한 알림을 받습니다",
    "Height" to "키",
    "Used for accurate calorie and distance estimates" to "칼로리와 거리를 더 정확하게 계산하는 데 사용합니다",
    "Weight" to "몸무게",
    "Used for accurate calorie estimates" to "칼로리를 더 정확하게 계산하는 데 사용합니다",
    "Age" to "나이",
    "Used for heart-rate zone calculations" to "심박수 구간을 계산하는 데 사용합니다",
    "Gender" to "성별",
    "Sync to Apple Health" to "Apple 건강과 동기화",
    "Sync to Health Connect" to "헬스 커넥트와 동기화",
    "Write steps, heart rate, sleep, and workouts to your phone's health platform" to "걸음 수, 심박수, 수면, 운동 기록을 휴대폰의 건강 앱에 저장합니다",
    "Health platform permissions not granted" to "건강 앱 권한이 허용되지 않았습니다",
    "Sync Now" to "지금 동기화",
    "Syncing..." to "동기화 중…",
    "Sync Pebble health data to phone" to "페블의 건강 기록을 휴대폰에 동기화",
    "Open Google Fit" to "Google 피트니스 열기",
    "View your synced health data in Google Fit" to "동기화한 건강 기록을 Google 피트니스에서 확인합니다",
    "Show Health Tab" to "건강 탭 표시",
    "Show Health instead of Notifications in the bottom bar" to "하단 메뉴에서 알림 대신 건강을 표시합니다",
    "View debug stats" to "진단 통계 보기",
    "Health statistics and averages" to "건강 통계 및 평균",
    "Warning: this will wipe all existing health data!" to "주의: 기존 건강 기록이 모두 삭제됩니다!",
    "Enable Weather" to "날씨 사용",
    "Fetch weather for the current location, for the Weather App (requires location permission)" to "날씨 앱에서 현재 위치의 날씨를 받아옵니다. 위치 권한이 필요합니다",
    "Weather Refresh Interval" to "날씨 갱신 간격",
    "Weather Pins" to "날씨 타임라인",
    "Add weather pins to timeline" to "타임라인에 날씨 추가",
    "Locations" to "지역",
    "Configure weather locations" to "날씨 지역 설정",
    "Use LAN developer connection" to "로컬 네트워크 개발자 연결 사용",
    "Allow connecting to developer connection over LAN, this is not secure and should only be used on trusted networks" to "로컬 네트워크에서 개발자 연결을 허용합니다. 보안 연결이 아니므로 신뢰하는 네트워크에서만 사용해 주십시오",
    "Show debug options" to "디버그 옵션 표시",
    "Show some extra debug options around the app - not useful for most users (contains some options which might break your watch)" to "개발용 옵션을 표시합니다. 일부 설정은 시계에 문제를 일으킬 수 있으니 주의해 주십시오",
    "PKJS Debugger" to "PKJS 디버거",
    "Watch settings sync" to "시계 설정 동기화",
    "Only for debugging - disables syncing settings with watch when disabled" to "개발용 옵션입니다. 끄면 시계와 설정을 동기화하지 않습니다",
    "Use Core OTA service" to "Core OTA 서비스 사용",
    "Check Core Devices service for Core watch firmware updates instead of Memfault (falls back to Memfault on failure)" to "Core Devices에서 펌웨어 업데이트를 확인합니다. 실패하면 Memfault를 사용합니다",
    "Offline Speech Recognition" to "오프라인 음성 인식",
    "Rebble speech recognition requires a Rebble subscription" to "Rebble 음성 인식을 사용하려면 구독이 필요합니다",
    "This device doesn't support system speech recognition" to "이 기기는 시스템 음성 인식을 지원하지 않습니다",
    "Cloud Only" to "클라우드만",
    "Cloud (with Local Fallback)" to "클라우드 우선, 실패하면 기기에서",
    "Local (with Cloud Fallback)" to "기기 우선, 실패하면 클라우드에서",
    "Rebble Only" to "Rebble만",
    "Rebble (with Local Fallback)" to "Rebble 우선, 실패하면 기기에서",
    "Local (with Rebble Fallback)" to "기기 우선, 실패하면 Rebble에서",
    "System (On-Device)" to "시스템 음성 인식",
    "Downloading in the background..." to "백그라운드에서 내려받는 중…",
    "Manage Offline Models" to "오프라인 모델 관리",
    "Note: Offline speech recognition is lower accuracy, consider using" to "오프라인 음성 인식은 정확도가 낮을 수 있습니다. 인터넷이 연결돼 있다면",
    "'Fallback only' mode to improve results when online" to "기기 내 인식을 보조 수단으로 사용하는 설정을 추천합니다",
    "Ignore other Pebble apps" to "다른 페블 앱 무시",
    "Allow connection even when there are other Pebble apps installed on this phone. Warning: this will likely make the connection unreliable if you are using BLE! We don't recommend enabling this" to "다른 페블 앱이 설치돼 있어도 연결합니다. BLE 연결이 불안정해질 수 있으므로 권장하지 않습니다",
    "Send app crashes" to "앱 오류 보고서 보내기",
    "This allows us to fix crashes in the mobile app - otherwise we don't know how often they are happening, or how to fix them" to "앱이 종료되는 문제의 빈도와 원인을 파악해 수정하는 데 도움이 됩니다",
    "Send watch analytics" to "시계 분석 정보 보내기",
    "Only for Core Devices watches. This allows us to measure metrics e.g. battery life, and debug watch crashes (otherwise we do not know whether they are regressions in reliability or performance)" to "Core Devices 시계에서만 사용합니다. 배터리 사용 시간과 시계 오류를 분석해 안정성·성능 문제를 찾는 데 도움이 됩니다",
    "Send app analytics" to "앱 분석 정보 보내기",
    "This allows us to track metrics e.g. connectivity, so that we can track different types of error and improve reliability" to "연결 상태 등의 정보를 분석해 오류를 찾고 연결 안정성을 높이는 데 도움이 됩니다",
    "Show notifications in phone logs" to "휴대폰 로그에 알림 표시",
    "Show sensitive content in phone logs" to "휴대폰 로그에 민감한 내용 포함",
    "Include unredacted personal information (notification content, calendar events, app names, etc) in logs" to "알림 내용, 캘린더 일정, 앱 이름 등 개인정보를 가리지 않고 로그에 포함합니다",
    "Verbose connection logging" to "자세한 연결 로그",
    "Detailed connectivity state machine logging (please don't enable this unless we ask you to)" to "연결 상태를 자세하게 기록합니다. 개발자가 요청한 경우에만 켜주십시오",
    "Verbose PPoG logging" to "자세한 PPoG 로그",
    "Detailed Pebble Protocol over GATT logging (please don't enable this unless we ask you to)" to "GATT 통신을 자세하게 기록합니다. 개발자가 요청한 경우에만 켜주십시오",
    "Re-publish GATT services after BT restore" to "블루투스 복원 후 GATT 서비스 다시 등록",
    "Reversed PPoG" to "역방향 PPoG",
    "Let the watch host the data connection when it supports it. Turn off to use the older phone-hosted mode. Reconnect for this to take effect" to "지원하는 시계가 데이터 연결을 담당하도록 합니다. 끄면 휴대폰이 담당합니다. 다시 연결해야 적용됩니다",
    "Bluetooth state restoration" to "블루투스 상태 복원",
    "Let iOS relaunch the app to restore the watch connection. Takes effect on next app launch" to "iOS가 앱을 다시 실행해 시계 연결을 복원하도록 합니다. 다음 실행부터 적용됩니다",
    "Passive reconnection mode" to "재연결 대기 모드",
    "After a failed connection, wait for the watch to become available instead of retrying repeatedly" to "연결에 실패하면 계속 재시도하지 않고 시계가 연결 가능해질 때까지 기다립니다",
    "Filter BLE watch scans by UUID" to "UUID로 BLE 시계 검색 필터링",
    "Disable this only if BLE scans are not finding your Core watch or Pebble 2" to "BLE 검색에서 Core 시계나 Pebble 2를 찾지 못할 때만 꺼주십시오",
    "Post test notification" to "테스트 알림 보내기",
    "Create a test notification, with actions" to "동작 버튼이 있는 테스트 알림을 만듭니다",
    "Watch type for unknown devices" to "알 수 없는 기기의 시계 종류",
    "Force JSCore GC" to "JSCore 메모리 정리",
    "Disable FW update notifications" to "펌웨어 업데이트 알림 끄기",
    "Ignore notifications for users who sideload their own firmware" to "펌웨어를 직접 설치하는 사용자를 위해 업데이트 알림을 끄는 옵션입니다",
    "Do immediate background sync" to "지금 백그라운드 동기화",
    "Sync firmware updates, locker, etc manually now (happens regularly automatically)" to "펌웨어 업데이트와 보관함 등을 지금 동기화합니다. 평소에는 자동으로 실행됩니다",
    "Copy PKJS account token" to "PKJS 계정 토큰 복사",
    "Use experimental plugins" to "실험용 플러그인 사용",
    "Enable the new plugins API. This is an experimental feature under development - not recommended unless you know what you are doing (API is unstable, and can expose private data until a permission system is implemented)" to "개발 중인 새 플러그인 기능을 사용합니다. 동작이 불안정하고 개인정보가 노출될 수 있어 일반 사용은 권장하지 않습니다",
    "Sign Out - Pebble Account" to "Pebble 계정 로그아웃",
    "User signed out" to "로그아웃했습니다",
    "Failed to sign out" to "로그아웃하지 못했습니다",
    "Sign In - Pebble Account" to "Pebble 계정 로그인",
    "Sign Out - Rebble" to "Rebble 로그아웃",
    "Sign out of your Rebble account" to "Rebble 계정에서 로그아웃합니다",
    "Auto-Resume Firmware Updates" to "펌웨어 업데이트 자동 재개",
    "Automatically continue an interrupted firmware update when the watch reconnects" to "시계가 다시 연결되면 중단된 펌웨어 업데이트를 이어서 진행합니다",
    "Show Watch Onboarding" to "시계 초기 설정 열기",
    "Show Ring Onboarding" to "링 초기 설정 열기",
    "Emulate Timeline Webservice" to "타임라인 웹서비스 대신 로컬 저장",
    "Intercept calls to Timeline webservice, instead inserting pins locally, immediately" to "타임라인 웹서비스 요청을 받아 항목을 기기에 바로 저장합니다",
    "Use Pebble Weather Service when apps are broken" to "날씨 앱 오류 시 Pebble 날씨 서비스 사용",
    "If old apps are using a broken weather API, attempt to use the Pebble Weather Service instead (will only work for some apps which use OpenWeather API)" to "오래된 앱의 날씨 API가 작동하지 않으면 Pebble 날씨 서비스로 대신 요청합니다. 일부 OpenWeather 앱에서만 작동합니다",
    "Show watch connection debug info" to "시계 연결 진단 정보 표시",
    "Extra debug info on devices tab" to "기기 탭에 진단 정보를 추가합니다",
    "Seek instead of Skip for Podcasts" to "팟캐스트에서 곡 넘기기 대신 탐색",
    "Icons will only update on updated PebbleOS version" to "아이콘은 업데이트된 PebbleOS에서만 바뀝니다",
    "Decrease" to "줄이기",
    "Increase" to "늘리기",
    "Copy Account Token" to "계정 토큰 복사",
    "Select language" to "언어 선택",
    "Search languages" to "언어 검색",
    "Note: Selecting a language may improve accuracy for that language but not all languages on this list are guaranteed to be supported." to "언어를 지정하면 인식 정확도가 좋아질 수 있습니다. 다만 목록의 모든 언어가 지원되는 것은 아닙니다.",
    "12 hours" to "12시간",
    "24 hours" to "24시간",
    "15 minutes" to "15분",
    "30 minutes" to "30분",
    "1 hour" to "1시간",
    "Refresh Collections" to "보관함 새로고침",
    "Appstore Sources" to "앱스토어 소스",
    "Couldn't open login page" to "로그인 페이지를 열지 못했습니다",
    "Add Source" to "소스 추가",
    "Delete Source" to "소스 삭제",
    "Watchapp Collections" to "시계 앱 모음",
    "Watchface Collections" to "워치페이스 모음",
    "Add Appstore Source" to "앱스토어 소스 추가",
    "Name" to "이름",
    "Source URL" to "소스 주소",
    "Featured Apps" to "추천 앱",
    "Offline voice recognition" to "오프라인 음성 인식",
    "We've improved offline voice recognition. Open the app to update the model." to "오프라인 음성 인식이 개선됐습니다. 앱에서 모델을 업데이트해 주십시오.",
    "Updating voice model" to "음성 모델 업데이트 중",
    "Update failed" to "업데이트 실패",
    "Voice model update" to "음성 모델 업데이트",
    "Later" to "나중에",
    "Update" to "업데이트",
    "Downloading the updated model. This may take a few minutes." to "새 모델을 내려받고 있습니다. 몇 분 정도 걸릴 수 있습니다.",
    "The download didn't finish. Check your connection and try again." to "다운로드를 마치지 못했습니다. 인터넷 연결을 확인한 뒤 다시 시도해 주십시오.",
    "We've improved on-device voice recognition. Update the model to keep transcribing offline." to "기기 내 음성 인식이 개선됐습니다. 오프라인에서 계속 사용하려면 모델을 업데이트해 주십시오.",
    "Alpha Test Instructions" to "알파 테스트 안내",
    "What's new in the app" to "앱의 새로운 기능",
    "Sending bug report" to "버그 제보를 보내는 중",
    "Gathering Watch Logs" to "시계 로그를 모으는 중",
    "Success" to "완료",
    "Report Sent!" to "제보를 보냈습니다!",
    "Send Report" to "제보 보내기",
    "Please describe the bug" to "어떤 문제가 있었는지 알려주십시오",
    "This is a:" to "문제가 생긴 기기:",
    "Index bug" to "Index 문제",
    "Watch bug" to "시계 문제",
    "You must sign in to submit a bug report" to "버그를 제보하려면 로그인해 주십시오",
    "Include recording" to "녹음 포함",
    "Include recent recordings" to "최근 녹음 포함",
    "Take Watch Screenshot" to "시계 스크린샷 촬영",
    "Capturing screenshot..." to "스크린샷 촬영 중…",
    "Watch screenshot" to "시계 스크린샷",
    "Retake" to "다시 촬영",
    "How to submit a great bug report" to "문제를 잘 전달하는 방법",
    "Tap to see what's working and what's still in development" to "지원하는 기능과 개발 중인 기능 보기",
    "Please note that logs + device info will be sent with this report" to "제보와 함께 로그 및 기기 정보가 전송됩니다",
    "You can follow up on an existing bug report by adding more logs or information:" to "기존 제보에 로그나 정보를 추가할 수 있습니다:",
    "Remove Attachments" to "첨부 파일 삭제",
    "Remove Images" to "사진 삭제",
    "Clear attachments" to "첨부 파일 비우기",
    "Attach an image" to "사진 첨부",
    "Add Images" to "사진 추가",
    "Local" to "기기 내",
    "Remote" to "원격",
    "Platform" to "플랫폼",
    "Failed to send bug report" to "버그 제보를 보내지 못했습니다",
    "Authentication failed" to "인증 실패",
    "Network error. Please check your connection and try again." to "네트워크 오류입니다. 인터넷 연결을 확인한 뒤 다시 시도해 주십시오.",
    "Request timed out. Please try again." to "응답 시간이 초과됐습니다. 다시 시도해 주십시오.",
    "Unable to submit bug report. Please try again later." to "버그를 제보하지 못했습니다. 잠시 후 다시 시도해 주십시오.",
    "Gathering watch logs..." to "시계 로그를 모으는 중…",
    "Bug report successfully uploaded!" to "버그 제보를 올렸습니다!",
    "An unexpected error occurred" to "예상하지 못한 오류가 발생했습니다",
    "Unable to prepare file uploads. Please check your connection and try again." to "파일 업로드를 준비하지 못했습니다. 인터넷 연결을 확인한 뒤 다시 시도해 주십시오.",
    "Unable to prepare file uploads. Please try again later." to "파일 업로드를 준비하지 못했습니다. 잠시 후 다시 시도해 주십시오.",
    "Failed to upload attachments" to "첨부 파일을 올리지 못했습니다",
    "Network error during file upload. Please check your connection and try again." to "파일을 올리는 중 네트워크 오류가 발생했습니다. 인터넷 연결을 확인한 뒤 다시 시도해 주십시오.",
    "File upload timed out. Please try again with a better connection." to "파일 업로드 시간이 초과됐습니다. 연결 상태가 좋은 곳에서 다시 시도해 주십시오.",
    "Unable to upload attachments. Please try again later." to "첨부 파일을 올리지 못했습니다. 잠시 후 다시 시도해 주십시오.",
    "Watches (most recently connected first):" to "시계 목록(최근 연결순):",
    "Get Started!" to "시작하기!",
    "Waiting for your Pebble to restart.." to "페블이 다시 시작하기를 기다리는 중…",
    "Waiting for your Pebble to connect.." to "페블이 연결되기를 기다리는 중…",
    "Checking for PebbleOS updates.." to "PebbleOS 업데이트 확인 중…",
    "Updating your watch to the latest version of PebbleOS..." to "시계를 최신 PebbleOS로 업데이트하는 중…",
    "Once your Pebble is connected, we'll get it set up" to "페블이 연결되면 설정을 시작합니다",
    "Add some Watchfaces" to "워치페이스 추가하기",
    "Add some Apps" to "앱 추가하기",
    "Get more apps from the Pebble App Store!" to "페블 앱스토어에서 더 많은 앱을 찾아보십시오!",
    "Install a language pack" to "언어팩 설치",
    "Choose Language" to "언어 선택",
    "Configure your watch" to "시계 설정",
    "Configure more in Settings" to "설정에서 더 바꿔보십시오",
    "Finished" to "완료",
    "Please sign in to view your bug reports" to "내 버그 제보를 보려면 로그인해 주십시오",
    "No bug reports found" to "아직 제보한 버그가 없습니다",
    "Uploading attachment" to "첨부 파일을 올리는 중",
    "Attach More Logs" to "로그 추가",
    "Fetching and uploading new logs" to "새 로그를 가져와 올리는 중",
    "Upload More Logs" to "로그 추가 업로드",
    "Get Started" to "시작하기",
    "I have a:" to "사용하는 기기:",
    "Skip" to "건너뛰기",
    "Connect a Pebble!" to "페블을 연결해 주십시오!",
    "Exit onboarding" to "초기 설정 나가기",
    "Not working? Report a bug" to "제대로 작동하지 않습니까? 버그 제보하기",
    "Open bug report" to "버그 제보 열기",
    "Please wait for the download to complete before trying." to "다운로드가 끝나면 시도해 주십시오.",
    "Try it out! Hold the button and speak into the ring, then release." to "직접 해 보십시오! 버튼을 누른 채 링에 말한 뒤 놓아주십시오.",
    "Receiving recording..." to "녹음을 받는 중…",
    "Recording too short! Try holding the button a bit longer." to "녹음이 너무 짧습니다! 버튼을 조금 더 길게 눌러주십시오.",
    "Transfer failed" to "전송 실패",
    "No action taken" to "실행한 동작 없음",
    "Thinking..." to "처리 중…",
    "Meet Index 01" to "Index 01 소개",
    "What if I find a bug?" to "버그를 발견하면 어떻게 합니까?",
    "Is it always listening?" to "항상 듣고 있습니까?",
    "What can I record?" to "무엇을 녹음할 수 있습니까?",
    "Where's the microphone?" to "마이크는 어디에 있습니까?",
    "How do I use it?" to "어떻게 사용합니까?",
    "What if I want to ditch my phone?" to "휴대폰 없이 사용할 수 있습니까?",
    "How do I charge it?" to "어떻게 충전합니까?",
    "Continue to setup" to "설정 계속하기",
    "Sign in to continue" to "로그인하고 계속하기",
    "On-device speech recognition" to "기기 내 음성 인식",
    "Speech recognition" to "음성 인식",
    "Ring Button" to "링 버튼",
    "Choose what each press does. You can change this later in Index settings." to "버튼을 눌렀을 때 실행할 동작을 골라주십시오. 나중에 Index 설정에서 바꿀 수 있습니다.",
    "Index Agent" to "Index 도우미",
    "Pick which actions Index can take, and where notes and reminders are saved." to "Index가 실행할 동작과 메모·리마인더를 저장할 곳을 골라주십시오.",
    "Secondary action" to "보조 동작",
    "Click before holding to perform a secondary voice action." to "한 번 누른 뒤 길게 누르면 보조 음성 동작을 실행합니다.",
    "Backups" to "백업",
    "Try it out" to "직접 해보기",
    "Finish setup" to "설정 마치기",
    "You can change these later in settings" to "나중에 설정에서 바꿀 수 있습니다",
    "Sign in to back up your recordings." to "녹음을 백업하려면 로그인해 주십시오.",
    "Cloud Backup" to "클라우드 백업",
    "Recordings sync to the cloud" to "녹음을 클라우드에 동기화합니다",
    "Recordings stay on this device only" to "이 기기에만 녹음을 저장합니다",
    "Encrypt Backups" to "백업 암호화",
    "Only you can read your backups" to "나만 백업을 볼 수 있습니다",
    "Encrypt Index data so only you can read it" to "나만 읽을 수 있도록 Index 데이터를 암호화합니다",
    "Turn on Cloud Backup to set up encryption" to "암호화를 설정하려면 클라우드 백업을 켜주십시오",
    "On-device" to "기기 내",
    "Recommended - private, stays on this iPhone" to "추천 — 이 iPhone 안에서만 처리합니다",
    "Cloud only" to "클라우드만",
    "Best performance, requires connection" to "가장 좋은 성능, 인터넷 연결 필요",
    "Cloud, with local fallback" to "클라우드 우선, 실패하면 기기에서",
    "Recommended, 400MB download" to "추천, 400MB 다운로드 필요",
    "Local only" to "기기에서만",
    "Complete privacy, 400MB download" to "외부로 전송하지 않음, 400MB 다운로드 필요",
    "Supported languages" to "지원 언어",
    "Authentication failed. Please sign in with Google and try again." to "인증에 실패했습니다. Google로 로그인한 뒤 다시 시도해 주십시오.",
    "Email and description are required" to "이메일과 설명을 입력해 주십시오",
    "Please fill in both your email and bug description before submitting." to "보내기 전에 이메일과 문제 설명을 모두 입력해 주십시오.",
    "Email" to "이메일",
    "Please enter a valid email address." to "올바른 이메일 주소를 입력해 주십시오.",
    "Please describe the bug you encountered." to "어떤 문제가 있었는지 알려주십시오.",
    "Unable to submit bug report. Please try again." to "버그를 제보하지 못했습니다. 다시 시도해 주십시오.",
    "Unable to submit bug report. Please check your connection and try again." to "버그를 제보하지 못했습니다. 인터넷 연결을 확인한 뒤 다시 시도해 주십시오.",
    "Report a bug" to "버그 제보",
    "Connected" to "연결됨",
    "Connected (Factory)" to "연결됨(복구 모드)",
    "Disconnected" to "연결 안 됨",
    "Disconnecting" to "연결 해제 중",
    "Connecting" to "연결 중",
    "Negotiating" to "연결 준비 중",
    "Rebooting after update - Negotiating" to "업데이트 후 다시 시작 — 연결 준비 중",
    "Rebooting after update - Waiting" to "업데이트 후 다시 시작 — 대기 중",
    "Sign in with Google" to "Google로 로그인",
    "Sign in with Apple" to "Apple로 로그인",
    "Sign in with GitHub" to "GitHub로 로그인",
    "Sign in anyway" to "계속 로그인",
    "Sign in to existing account?" to "기존 계정에 로그인하시겠습니까?",
    "Battery Life" to "배터리 사용 시간",
    "Check for Updates" to "업데이트 확인",
    "Checking for updates..." to "업데이트 확인 중…",
    "Connected to CloudPebble" to "CloudPebble에 연결됨",
    "Create a Core Dump" to "코어 덤프 생성",
    "Create a Core Dump?" to "코어 덤프를 생성하시겠습니까?",
    "Dev Connection" to "개발자 연결",
    "Downloading Models" to "모델 다운로드 중",
    "Factory reset" to "공장 초기화",
    "Factory reset?" to "공장 초기화하시겠습니까?",
    "Firmware Update Debug" to "펌웨어 업데이트 진단",
    "If the app crashes every time you press Connect, try checking" to "연결을 누를 때마다 앱이 종료된다면 다음 설정을 확인해 주십시오",
    "Mutes the phone's own call vibration/sound while the watch is connected" to "시계가 연결돼 있는 동안 휴대폰의 전화 소리와 진동을 끕니다",
    "Mutes the phone's own notification vibration/sound while the watch is connected" to "시계가 연결돼 있는 동안 휴대폰의 알림 소리와 진동을 끕니다",
    "Notification logging, to diagnose processing/deduplication issues (does not include any content/app name/personal information unless separately enabled below)" to "알림 처리와 중복 제거 문제를 확인할 로그를 기록합니다. 아래에서 별도로 켜지 않으면 알림 내용·앱 이름·개인정보는 포함하지 않습니다",
    "Notifications won't be sent to watch if phone is in Do Not Disturb mode (unless configured for that app/person in phone settings)" to "휴대폰이 방해 금지 상태이면 시계에 알림을 보내지 않습니다. 휴대폰 설정에서 예외로 허용한 앱과 연락처는 제외합니다",
    "Okay" to "확인",
    "One or more other PebbleOS companions apps are installed. Please " to "다른 페블 연결 앱이 설치돼 있습니다. ",
    "Ping Watch" to "시계 응답 확인",
    "Remember to unpair any other phones from your watch before connecting (Settings/Bluetooth)" to "연결하기 전에 시계의 설정 > 블루투스에서 다른 휴대폰과의 연결을 해제해 주십시오",
    "Reset into PRF" to "복구 모드로 다시 시작",
    "Reset into PRF?" to "복구 모드로 다시 시작하시겠습니까?",
    "Send Notification" to "알림 보내기",
    "Store notifications from disabled apps/channels, to allow viewing them in history" to "알림을 끈 앱과 채널의 알림도 기록에서 볼 수 있도록 저장합니다",
    "This feature requires downloading additional machine learning models. " to "이 기능을 쓰려면 추가 음성 인식 모델을 내려받아야 합니다. ",
    "This might take a few minutes on a slow connection..." to "인터넷 연결이 느리면 몇 분 정도 걸릴 수 있습니다…",
    "This will capture the current state of the watch - then the watch will reset. Send a bug report after reconnection to send us the core dump. Only use this if we asked you to!" to "시계의 현재 상태를 저장한 뒤 다시 시작합니다. 다시 연결되면 버그 제보를 보내 덤프를 전달해 주십시오. 개발자가 요청한 경우에만 사용해 주십시오!",
    "This will reset the watch into recovery mode. Not for general public use." to "시계를 복구 모드로 다시 시작합니다. 일반적인 사용에는 필요하지 않습니다.",
    "This will wipe the watch completely" to "시계의 모든 데이터가 삭제됩니다",
    "To unpair, find the Index 01 in your Bluetooth settings and choose to forget/unpair it." to "연결을 해제하려면 블루투스 설정에서 Index 01을 찾아 등록 해제를 눌러주십시오.",
    "Use miles/feet/inches/lb and Fahrenheit instead of metric units" to "미터법 대신 마일·피트·인치·파운드·화씨를 사용합니다",
    "Write Notification" to "알림 작성"
)
